---
name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-latex-recommended
          version: 1.0
      - run: make all
      - run: mkdir -p dist
      - run: echo '<embed src="document.pdf" type="application/pdf" />' > dist/index.html
      - run: cp document.pdf dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
