---
name: CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-latex-recommended texlive-xetex latexmk texlive-fonts-extra texlive-bibtex-extra biber
          version: 1.0

      - run: sudo apt-get install --reinstall texlive-xetex
      - run: make all
      - name: Create site
        run: mkdir -p dist; echo '<html style="padding:0; margin 0;"><body style="padding:0; margin 0;"><embed src="document.pdf" type="application/pdf" width="100%" height="100%"/> </body></html>' > dist/index.html; cp document.pdf dist

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
